on: [push, pull_request]

name: CI

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      CC: gcc
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: cargo build --verbose
      - run: cargo test
#      - run: cargo clippy -- -D warnings
      - run: cargo fmt --all -- --check
