on: [push, pull_request]

name: CI

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --verbose
      - run: cargo test
#      - run: cargo clippy -- -D warnings
      - run: cargo fmt --all -- --check
