name: ECOZ2 Rust Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_linux:
    runs-on: ubuntu-latest  # https://github.com/actions/virtual-environments/issues/1816

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build linux
      run: |
        CC=gcc cargo build --verbose --release
        cd target/release/
        zip "${{github.workspace}}/ecoz2rs-linux.zip" ecoz2

    - uses: actions/upload-artifact@v2
      with:
        name: ecoz2rs-linux.zip
        path: "${{github.workspace}}/ecoz2rs-linux.zip"

  build_macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build macos
        run: |
          CC=gcc-13 cargo build --verbose --release
          cd target/release/
          zip "${{github.workspace}}/ecoz2rs-macos.zip" ecoz2

      - uses: actions/upload-artifact@v2
        with:
          name: ecoz2rs-macos.zip
          path: "${{github.workspace}}/ecoz2rs-macos.zip"

  release:
    needs: [build_linux, build_macos]
    runs-on: macos-latest

    steps:
    - name: Get linux release
      uses: actions/download-artifact@v2
      with:
        name: ecoz2rs-linux.zip

    - name: Get macos release
      uses: actions/download-artifact@v2
      with:
        name: ecoz2rs-macos.zip

    - name: Complete release
      uses: sondreb/action-release@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
        prerelease: true
        body: 'This is a pre-release'
        name: "Draft Release ${{ github.ref }}"
        tag: ${{ github.ref }}
        files: "ecoz2rs-linux.zip;ecoz2rs-macos.zip"
